# Rollback a PHP agent release from testing or production.
# This step verifies the credentials.

---
name: php-rollback-check-dir

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ gha-testing ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      REPO:
        description: "Required -- the repository to modify."
        required: true
        default: ''
        type: choice
        options:
        - testing
        - production
  # GHA: Facilitating reusable workflow in case required
  workflow_call:
    inputs:
      REPO:
        description: "Required -- the repository to modify. Either testing, or production"
        required: true
        default: 'testing'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  php-rollback-check-dir:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
    # container:  ## kds = testing using private docker image
    #   image: kentonshade/mycirrus_1:ubuntu-focal-starter
    #   credentials:
    #      username: ${{ secrets.DOCKER_REPO_USER }}
    #      password: ${{ secrets.DOCKER_USER_PASS }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - name: Checkout PHP Deployment Repo   ## NOT POSSIBLE as of 05/13/2021 from GHE
        uses: actions/checkout@v3
        with:
          repository: newrelic/php-agent-php_deployment
          ref: master
          token: ${{ secrets.API_CLI_TOKEN }}
          # path: <path>

      # GHA: set AWS credentials
      # GHA: Check updates to this action
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Verifies the credentials, list content
      - name: Verify the credentials
        run: |
          aws s3 ls s3://nr-downloads-main/php_agent/release/