---

# GHA: Jenkins job:
# https://phpagent-build.pdx.vm.datanerd.us/job/php-release-tarballs/configure
# https://issues.newrelic.com/browse/NR-6481
# This is WIP.

name: php-release-tarballs

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ['NEW release_CI (php-release-agent)']
    branches:
      - gha-dev
      - dev
      - main
    types:  ## Review if this is the comperehensive types available
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # GHa Need to determine OS to use.  Container?  GH Runner?
  php-release-tarballs:
    runs-on: ubuntu-latest
    env:
      GROUP: 'mycirrus'
      IMAGE: 'newrelic:nr-centos6-1.2'
      # GHA required for package.sh, but we need to verify/acceptance criteria
      JOB_NAME: 'php-release-tarballs'
    container:  ## GHA: testing using private docker image
      image: mycirrus/newrelic:nr-centos8-1.1
      credentials:
        username: ${{ secrets.DOCKER_REPO_USER }}
        password: ${{ secrets.DOCKER_USER_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # GHA: Required to return latest release run
      # We will need to install gh for this container
      - name: Get dependent workflow ID
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ always() }}
        run: |
          echo "${ACCESS_TOKEN}" | gh auth login --with-token
          gh auth status
          echo "RUN_ID=$(gh run list -w 20074295 -L 1 | cut -f 7)" >> $GITHUB_ENV

      - name: Download combined-artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: NEW-release-build.yml
          branch: gha-dev
          run_id: ${{ env.RUN_ID }}
          path: combined-artifacts
          repo: ${{github.repository}}

      # Runs a set of commands using the runners shell
      - name: Check our directories
        run: |
          tree -a combined-artifacts/

      # Get the directories ready for buid-redhat.sh
      - name: Consolidate releases
        run: |
          mkdir releases
          cp -R combined-artifacts/combined-releases-*/alpine/* releases/
          cp -R combined-artifacts/combined-releases-*/centos/* releases/
          tree -a releases/

      # Get the directories ready for buid-redhat.sh
      - name: Change gpg
        run: |
          mv /usr/bin/gpg /usr/bin/gpg.bak
          sudo ln -s /usr/bin/gpg1 /usr/bin/gpg
          gpg --version

      - name: Call package.sh
        run: |
          echo "Calling build-redhat.sh"
          ./packaging/package.sh

      # Check for new content in releases
      - name: Check for new content in releases
        run: |
          tree -a releases/
