# GHA: Initial test workflow

---

name: SNYK Testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # workflow_run:
  #   workflows: ['NEW release_CI (php-release-agent)']
  #   branches:
  #     - gha-dev
  #     - dev
  #     - main
  #   types: ## Review if this is the comperehensive types available
  #     - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  snyk-testing:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      ## GHA:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low
          # GHA: Receiving errors related to path
          command: test --file=tests/include/newrelic-integration/package.json
          json: false  # Optional
